### ISSUE TITLE
Add the Alice TTS

### ISSUE THREAD

**Issue by SitkoAleksandr** [efa2000/node-red-contrib-alice#1]
If it is possible, I ask you to add a possibility to use Alice TTS engine for this node.

**Comment by efa2000** [comment]
> If it is possible, I ask you to add a possibility to use Alice TTS engine for this node.

Unfortunately, this is not possible at the moment.
This module integrates with Alice’s Smart Home skill, which does not provide access to Alice’s TTS.
To use TTS, a separate integration module with Alice’s generic skills is required.

**Comment by twocolors** [comment]
@efa2000 this module (https://github.com/AlexxIT/YandexStation) use some skills ?

**Comment by efa2000** [comment]
Very interesting.
Alice’s skills are not used here.
It uses direct access to the Yandex Station API
I'll think about it. But this is definitely not in this module. It will be necessary to create a separate module

**Comment by twocolors** [comment]
thx, will wait.

**Comment by efa2000** [comment]
Unfortunately, I will not be able to implement Alice TTS in this project
