### ISSUE TITLE
Нода Mode

### ISSUE THREAD

**Issue by TomasDlg** [efa2000/node-red-contrib-alice#10]
1)Планируется ли добавление ноды Mode?
evices.capabilities.mode
Переключение режимов работы устройства, например, переключение между температурными режимами работы кондиционера: «Охлаждение», «Нагрев» или «Авто».
2)Прошу добавить возможность изменения параметра retrievable в настройка устройства так как имею несколько устройств без определения их состояния.

**Comment by efa2000** [comment]
да, планирую, но чуть позже 
не совсем понимаю чем Вас ограничивает отсутствие регулировки параметра retrievable т.к. даже если ваше устройство само не отдает статус, возвращается последний выставленный через алису статус

**Comment by kolohan** [comment]
Есть ли какой то гипотетический срок когда можно ожидать ноду Mode.

**Comment by efa2000** [comment]
Проект не коммерческий и делаю его по настроению и возможности 
думаю до конца июня добавлю mode

**Comment by kolohan** [comment]
В любом случае огромный респект за palette, с его помощью удалось пропихнуть кондиционер подключенный по modbus к wirenboard в алису и работает отлично, осталось разобраться с режимами работы, так что каждый день захожу проверить не появилась ли нода mode.

**Comment by efa2000** [comment]
Наконец удалось доделать node для режима работы

**Comment by efa2000** [comment]
версия 0.4.1

**Comment by kadkin-a** [comment]
А как добавить дополнительные режимы в Mode type - Programm? Н

Например в телевизоре добавить программы Youtube, кинопоиск и т.д. И сразу вписать любимые телеканалы?  То есть добавить кастомные режимы в меню программы. 
В программировании не силен, можно какой нибудь пример
