### ISSUE TITLE
Не могу настроить

### ISSUE THREAD

**Issue by Serhioromano** [efa2000/node-red-contrib-alice#118]
Прошу прощения, может я тупой, но я 20 лет в технологиях и не могу это настроить. 

> Добавьте в свою схему устройства и умения Алисы и зарегистрируйтесь на вкладке настройки

Хоть убей не могу найти настройки где можно зарегистрироваться. Даже понять не могу это в яндексе или NR нужно регистрироваться? В мобильном приложении авторизовался, добавляю навык NR он мне выводит логин пароль а что там писать? Логин в яндексе? Или нужен отдельный акаунт?

Можете снять видео инструкцию короткую.

**Comment by rzimin** [comment]
В NR надо нажать на зарегистрироваться - это создать учетную запись на node-red-alice.ru
Дальше эти данные вводить в NR
