### ISSUE TITLE
Фантомные устройства

### ISSUE THREAD

**Issue by aleksandrdobrynin** [efa2000/node-red-contrib-alice#12]
Если добавить устройство и удалить его затем из Node-RED, то после обновления списка устройств в приложении Яндекс, удаленные устройства снова появляются. Как окончательно удалить несуществующие устройства?

**Comment by JonnyLuz** [comment]
Поддерживаю

**Comment by efa2000** [comment]
Да, тоже заметил такое поведение 
Но, здесь похоже проблема на стороне яндекса 
проверил, сервис возвращает правильный список устройств, но сам яндекс его почему то не удаляет 

Написал в поддержку Яндекса, жду от них ответа

**Comment by efa2000** [comment]
Поддержка ответила, что автоудаление не предусмотренно :(
Предлагают удалять вручную в приложении Яндекса
Цитата:
"Уточнил информацию у коллег. Дело в том, что устройства не исчезают при обновлении списка устройств, т.е автоматического удаления не предусмотрено. Оно осуществляется только вручную."

**Comment by aleksandrdobrynin** [comment]
> Поддержка ответила, что автоудаление не предусмотренно :(
> Предлагают удалять вручную в приложении Яндекса
> Цитата:
> "Уточнил информацию у коллег. Дело в том, что устройства не исчезают при обновлении списка устройств, т.е автоматического удаления не предусмотрено. Оно осуществляется только вручную."

А если удалить устройство вручную, то оно появится при следующей синхронизации.

У меня были устройства с именами в плагине "зелёный" и "лампа". Так вот, я пробросил их через плагин в Яндекс. Все работало. Затем я удалил Node-RED и развернул его заново на другой малине. Опять пробросил устройства с такими именами. В итоге, устройство с именем "зелёный" не задублировалось, а вот устройство с именем "лампа" стало два.

**Comment by aleksandrdobrynin** [comment]
А вот если завести новую учетную запись в плагине, то список устройств обнуляется.

**Comment by efa2000** [comment]
> > Поддержка ответила, что автоудаление не предусмотренно :(
> > Предлагают удалять вручную в приложении Яндекса
> > Цитата:
> > "Уточнил информацию у коллег. Дело в том, что устройства не исчезают при обновлении списка устройств, т.е автоматического удаления не предусмотрено. Оно осуществляется только вручную."
> 
> А если удалить устройство вручную, то оно появится при следующей синхронизации.
> 
> У меня были устройства с именами в плагине "зелёный" и "лампа". Так вот, я пробросил их через плагин в Яндекс. Все работало. Затем я удалил Node-RED и развернул его заново на другой малине. Опять пробросил устройства с такими именами. В итоге, устройство с именем "зелёный" не задублировалось, а вот устройство с именем "лампа" стало два.

> А вот если завести новую учетную запись в плагине, то список устройств обнуляется.

Да, такое поведение вполне логично. 
есть устройства связанные с вашей учетной записью в плагине 
и есть устройства связанные с вашей учеткой в Яндексе 

что бы удалить устройства связанные с учеткой в плагине, необходимо удалить ноду в Node-Red и нажать деплой (если просто снести Node-red то связки останутся и реально к этим девайсам потом не получится подключится, спасет только новая учетка)
а вот что бы удалить устройства связанные с учеткой Яндекса, нужно удалить устройство из приложения Яндекс 

Я подумаю как чистить старые устройства, но из Яндекса, все равно придется удалять ручками

**Comment by aleksandrdobrynin** [comment]
Это было бы очень круто иметь такую возможность, каждый раз при переустановке НР не придётся думать, что нужно не забыть снести устройства, которые прокинуты в Яндекс. Ну и учетки заводить на каждое развертывание так себе удовольствие )

**Comment by efa2000** [comment]
версии 0.3.6 добавлена возможность удалить старые устройства 
кнопка доступна с вкладки настройки логина и пароля

**Comment by aleksandrdobrynin** [comment]
У меня два новых инстанса node-red, в которых установлен плагин и прокинуты устройства в Яндекс. Фантомные устройства остались в node-red, которого не существует. Что будет, если я нажму кнопку удалить все устройства? Удалятся только фантомные или нет?

**Comment by efa2000** [comment]
после нажатия кнопки, будут удалены все устройства связанные с вашей учетной записью 
все устройства которые еще актуальны (созданы в node-red) будут пересозданы при нажатии deploy (id и настройки останутся прежними )
там после нажатия кнопки появится еще страница на которой описана инструкция

**Comment by aleksandrdobrynin** [comment]
> после нажатия кнопки, будут удалены все устройства связанные с вашей учетной записью
> все устройства которые еще актуальны (созданы в node-red) будут пересозданы при нажатии deploy (id и настройки останутся прежними )
> там после нажатия кнопки появится еще страница на которой описана инструкция

Не, не сработало. Сделал все по инструкции. Нажал Remove all devices в node-red, удалил фантомные устройства в яндексе, сделал фулл деплой в node-red, в яндексе нажал добавить устройства и обновил список, и снова подгрузились фантомные устройства.

**Comment by efa2000** [comment]
очень странно, а вы уверены, то те устройства которые вы называете фантомными у вас удалены с вкладки "Configuration nodes"?
![image](https://user-images.githubusercontent.com/6084441/83510727-25104000-a4d6-11ea-9c05-52fb2934cc62.png)

**Comment by Snarky73** [comment]
Отлично. А как их отсюда удалить?

**Comment by Snarky73** [comment]
Отлично, спасибо. Но надо бы это в документацию добавить, а то неочевидно.

**Comment by efa2000** [comment]
думал, что использование конфигурационных нод будет вполне понятен. Но вы правы добавлю еще и документацию

**Comment by aleksandrdobrynin** [comment]
> очень странно, а вы уверены, то те устройства которые вы называете фантомными у вас удалены с вкладки "Configuration nodes"?

Уверен. Самого NR уже нет просто. Т.е. устройства (фантомные) остались в Яндекс, но NR и соответственно Configuration Node уже не существует. Удаляю устройства из Яндекс, синхронизирую и устройства снова появляются.

**Comment by aleksandrdobrynin** [comment]
Получилось удалить фантомные устройства на последнем билде.

**Comment by maxgamlet** [comment]
Приветствую! 
У меня похожая ситуация. Не могу удалить устройства. 
Было заведено 2 аккаунта в node-red для экспериментов. Устройства были в обоих. Из первого аккаунта удалил все устройства и они успешно удалились из яндекса. Но со вторым так не прокатывает, т.к.  в нем устройств уже нет, а фантомные в яндексе после синхронизации появляются. Подскажите, что делать?

**Comment by maxgamlet** [comment]
> 

Кроме того, в моём релизе нет кнопки "удалить все устройства"

**Comment by ivan-habl** [comment]
Столкнулся с аналогичной проблемой клонирования устройств и пока не нашел решения.

**Comment by maxgamlet** [comment]
Мне пришлось завести новый акк на яндексе. Так же есть отдельный "тестовый"...

**Comment by ivan-habl** [comment]
Мне помог автор ПО, удалив вручную фантомные устройства. Я, в свою очередь, ответил донатом.

**Comment by maxgamlet** [comment]
Он это стандартными средствами делал или код ковырял?

**Comment by ivan-habl** [comment]
Я написал автору в личку в телеграм в офф. группе и далее он уже сам своими инструментами.
