### ISSUE TITLE
Давление отображается в бар независимо от указанной единицы

### ISSUE THREAD

**Issue by shadowpanther** [efa2000/node-red-contrib-alice#136]
Если в датчике давления указать любые единицы измерения, в приложении Алисы отображается та же цифровая величина, с единицей измерения бар.
<img width="452" alt="image" src="https://user-images.githubusercontent.com/675104/148755203-fa8b37ae-7227-4830-a48e-cabb59223515.png">
<img width="155" alt="image" src="https://user-images.githubusercontent.com/675104/148755232-83a8eb25-0e9e-49b7-8f9c-77286fa2dbca.png">

Зачем мне это нужно - давление отображается без дробных разрядов, и отображение атмосферного давления в 1 бар теряет всякий смысл:
<img width="163" alt="image" src="https://user-images.githubusercontent.com/675104/148755849-95f9e012-401e-45b5-9ef8-d5319eea92bd.png">

**Comment by efa2000** [comment]
после обновления единиц измерения необходимо обновлять список устройств в приложении Яндекса 
точность после запитой к сожалению регулируется на стороне интерфейса яндекса, из моего сервиса значения уходят с точностью до двух знаков после запятой

**Comment by shadowpanther** [comment]
Спасибо за подсказку, действительно после обновления через добавление устройств размерность меняется. В паскалях не очень удобно получилось (величина в районе 100000Pa, сам датчик отдает в hPa), конвертировал в более привычные для России мм рт.ст.
