### ISSUE TITLE
зависание Node-Red

### ISSUE THREAD

**Issue by CurikovMF** [efa2000/node-red-contrib-alice#14]
Добрый день, использую Ваш плагин, все вроде работает но есть одно но. после последнего обновления Node-Red зависает раз в 3-4 дня. 
полный деплой смещает зависание. Без Вашего плагина зависании не наблюдается

**Comment by gonczarov** [comment]
Подтверждаю! Зависает в  нод ред через несколько дней.

**Comment by efa2000** [comment]
подскажите, а зависают только ноды с вязанные с алисой или в принципе все норы в node-red?

**Comment by aleksandrdobrynin** [comment]
> подскажите, а зависают только ноды с вязанные с алисой или в принципе все норы в node-red?
> 
> и в целом как выражаются зависания ? какую версию плагина используете?

Весь нодред загружает ядро или всю малину на 100%.

**Comment by efa2000** [comment]
ок, 
видимо из за проверок на подключение 
отключил доп проверки подключения 
выложил версию 0.3.5

попробуйте, просто у меня данная проблема не воспроизводится :(
