### ISSUE TITLE
конвертировать RGB/HSV в HEX

### ISSUE THREAD

**Issue by RootShell-coder** [efa2000/node-red-contrib-alice#15]
Мое устройство понимает HEX цвет. Нода color может отправить RGB и HSV.
Я пытался установить node-red-contrib-color-convert с которого HSV возвращает "no output, normally means bad input" а RGB "Input not an array". Конвертировать функцией из RGB я не понимаю формат строки - разные цвета разная длинна. 
Любая помощь.

**Comment by efa2000** [comment]
проблема в том, что Яндекс принимает и отдает RGB в 24 битном формате 
вот тут хорошо описаны функции по конвертации [https://gist.github.com/lrvick/2080648](https://gist.github.com/lrvick/2080648) 
в вашем случае для конвертации из RGB (24bit) в HEX функция будет такая:

```js
var bin = msg.payload;
var r = bin >> 16;
var g = bin >> 8 & 0xFF;
var b = bin & 0xFF;
var hex = "#" + ((1 << 24) + (r << 16) + (g << 8) + b).toString(16).slice(1);
msg.payload = hex;
return msg;
```
просто после ноды Color поставьте ноду Function с этим кодом и на выходе получите HEX в формате "#ff0055"

**Comment by RootShell-coder** [comment]
Все работает.  Благодарю.

**Comment by efa2000** [comment]
отлично, рад был помочь
