### ISSUE TITLE
Не получается зарегистрироваться на вкладке настройки

### ISSUE THREAD

**Issue by Snarky73** [efa2000/node-red-contrib-alice#17]
Не пойму, как зарегистрироваться.

**Comment by efa2000** [comment]
не совсем понимаю с чем у вас трудности 
просто нажимаете зарегистрироваться, вводите email и пароль
после этого они подставятся автоматом в форму ввода 
и нажмите ок 

поясните в какой момент у вас возникают трудности ?

**Comment by Snarky73** [comment]
В браузере. В Edge не работает, только в Хром. Вопрос закрыт, спасибо.
