### ISSUE TITLE
0.3.8 Исчезла иконка ноды

### ISSUE THREAD

**Issue by aleksandrdobrynin** [efa2000/node-red-contrib-alice#18]
Нода Алисы потеряла иконку и теперь выглядит так. Это норма?
![image](https://user-images.githubusercontent.com/32413181/83411806-a2c64400-a421-11ea-86e4-063694acd5d3.png)

**Comment by efa2000** [comment]
нет, не нормально :(
съехали пути иконок 
поправил (версия 0.3.9)
