### ISSUE TITLE
Конфликт умений устройства

### ISSUE THREAD

**Issue by Snarky73** [efa2000/node-red-contrib-alice#19]
Не совсем уверен, что это сюда, может быть к Яндексу.
Проблема.
Есть рулонные шторы, которые умеют on|off (открыто/закрыто) и в range.
Если добавлять только ноду range шторы не понимают команду "открой/закрой шторы",  только в процентах. При добавлении ноды он/офф голосовые команды начинают работать, но на карточке устройства, которая для ручного управления, ползунок процентов становится неактивным если устройство в состоянии off (шторы закрыты). И чтобы активировать ползунок, нужно их "включить", то есть в реальности - открыть.
Как быть?

**Comment by efa2000** [comment]
спасибо за этот кейс 
изначально, действительно эта проблема была в интерфейсе Яндекса, но сейчас я проверил документацию и они это проблему решили добавив возможно не блокировать управление если on|off выключен.
я добавлю поддержку этого параметра к ноде on|off в ближайшем релизе

**Comment by efa2000** [comment]
в версии 0.3.10 добавлена возможность, что бы on|off не блокировала доступ к другим элементам управления в интерфейсе Яндекса 
НО обратите внимание, что при снятии этой галочки вы не сможете узнать включено или выключено сейчас это устройство 
![image](https://user-images.githubusercontent.com/6084441/83633951-62de9880-a5aa-11ea-8194-b3e4c449f210.png)
