### ISSUE TITLE
Зависание Node-RED

### ISSUE THREAD

**Issue by aleksandrdobrynin** [efa2000/node-red-contrib-alice#20]
Дважды за последние сутки, с установленным и настроенным плагином, NR зависает на двух малинах. Версия плагина 0.3.10

**Comment by efa2000** [comment]
честно говоря даже не могу предположить с чем может быть связано 
у меня ни на тестовом стенде, ни на боевой малине такого не возникает
Подскажите:
зависает весь Node-RED или полностью малина? 
какая Raspbery используется?
какая версия ОС на ней установлена?
Какая версия NodeJS ?
Какая версия Node-red?
Я правильно понимаю, что если удалить мой плагин то зависание не происходит?
Возможно конфликтует с другими плагинами, можете дать список других установленных плагинов?
Есть какие еще наблюдения когда и как это происходит? может пропадание Интернет или отправка каких то данных или еще какие либо событии ?

**Comment by aleksandrdobrynin** [comment]
1. Одно ядро уходит на 100%, процесс Node-RED
2. RPI 4B, 4GB

**Comment by CurikovMF** [comment]
У меня зависания прекратились после вашего фикса

**Comment by CurikovMF** [comment]
После обновления на 0.3.10 снова завис

**Comment by efa2000** [comment]
да, я тоже словил зависание с аналогичными симптомами 
все, что пока понятно оно возникает в момент когда пропал интернет и в этот момент если попробовать послать новой значение из Node-red в сервис, все зависает
проблема идет из стороннего модуля firebase/firestore возможно даже глубже из grpc-js 
посмотрю что можно сделать

**Comment by efa2000** [comment]
> Вчера поймал такую запись в логе:
(node:4936) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 online listeners added to [AliceService]. Use emitter.setMaxListeners() to increase limit

А вот это уже из другой оперы, с зависаниями точно не связано. 
я поправлю это

**Comment by efa2000** [comment]
в модуле firebase они перешли на новый grpc который и вызывает такое поведение 
пришлось понизить зависимость firebase до версии 7.13.2
ошибка пропала

версия сборки плагина 0.3.12
