### ISSUE TITLE
Статус переключателя

### ISSUE THREAD

**Issue by Lopatin-Viktor** [efa2000/node-red-contrib-alice#29]
Здравствуйте, как обновить статус переключателя, если включил устройство не через Алису, в итоге устройство включено, а Алиса не в курсе.

**Comment by efa2000** [comment]
Здравствуйте 
каждый раз когда у вашего устройства меняется статус (не через Алису) просто подавайте соответствующие значение на вход ноды Алисы, и в Интерфейсе Алисы будет отображаться правильный статус устройства

**Comment by Lopatin-Viktor** [comment]
Здравствуйте, Max, направляю Вам видео с моей проблемой, а также как устанавливается Алиса
 
https://drive.google.com/file/d/1nj_pu8e22GstSZxxl-5bnjfc4Yq8eITX/view?usp=sharing  
 
установка:  https://drive.google.com/file/d/1cTzNA_5mMgcrfb_sXgyWwhIGl4VigFWO/view?usp=sharing   
>Вторник, 23 июня 2020, 22:08 +03:00 от Max <notifications@github.com>:
> 
> 
>Здравствуйте
>каждый раз когда у вашего устройства меняется статус (не через Алису) просто подавайте соответствующие значение на вход ноды Алисы, и в Интерфейсе Алисы будет отображаться правильный статус устройства
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
https://homesolutionsystem.com/
Виктор Лопатин
Инженер
+79163871864

**Comment by efa2000** [comment]
Виктор, спасибо за видео 
Здесь как раз особенности реализации интерфейса самим Яндексом 
при входе в список устройств, он однократно обновляет статусы девайсов и больше не опрашивает
а вот если зайти внутрь самого устройства, там статус переодически опрашивается (в течении 1-5 сек, у меня ) и изменения состояния будут сразу видны
мой сервис хранит последнее полученную информацию о состоянии и тут же отдает её когда со стороны яндекса приходит опрос
