### ISSUE TITLE
Не удаляются устройства из Я.Дом

### ISSUE THREAD

**Issue by semikor** [efa2000/node-red-contrib-alice#38]
Доброго времени суток!
Перевез Node-Red с Windows10 на raspberry pi 4 через Экспорт-Импорт каждого флоу. После этого на Винде удалил и устройства и аккаунты. После обновления и запуска на Малинке в Яндекс доме каждое устройство из node-red-contrib-alice продублировалось, т.е. было 7шт стало 14шт с теми же именами, но (похоже которые почему-то остались от Винды) не рабочие и никак не удаляются. Стираю их в ЯДоме, но при следующем обновлении устройств Node-Red они опять появляются.
Сейчас на Малине удалил полностью все устройства и сам node-red-contrib-alice, Малину выключил, почистил где смог кеш, но даже с выключенной Малинкой при обновлении в ЯДоме устройств Node-Red эти 7 устройств опять появляются и нет ошибки, что сервер не доступен.
Т/п Яндекса ничем не смогла помочь, посоветовала обратиться к разработчику node-red-contrib-alice ))
Помогите, пожалуйста, удалить эти устройства из Node-Red! 
Очень не хочется менять аккаунт яндекса (многое завязано), а с этими фантомами очень не удобно продолжать (

**Comment by efa2000** [comment]
Доброго 

посмотри вот этот пост, там была аналогичная проблема, после которой в плагин была добавлена кнопка удалить все устройства https://github.com/efa2000/node-red-contrib-alice/issues/12 

если коротко, нужно зайти в настройку где вы вбивали логин и пароль, там есть кнопка удалить все устройства.
после её нажатия уделяться все устройства из базы данных на удаленном сервере, когда нажмете редеплой схемы, в базе создадуться только реально существующие устройства 

к сожалению, после этого нужно будет в интерфейсе яндекса их ручками поудалять, но фантомов больше создаваться не будет

**Comment by semikor** [comment]
Спасибо ОГРОМНОЕ!
Вотжешь блин... неделю промучился, а но эту кнопку не обратил внимания.

**Comment by efa2000** [comment]
рад был помочь :)
