### ISSUE TITLE
Соединение с сервером

### ISSUE THREAD

**Issue by TomasDlg** [efa2000/node-red-contrib-alice#4]
После кратковременного отключения интернет соединения автоматический не восстанавливает соединение с сервером. Приходится вручную восстанавливать соединение с сервером путем нажатия на кнопку Deploy или перезагружать node-red.

**Comment by efa2000** [comment]
да, нашел 
постараюсь исправить в ближайшем обновлении

**Comment by TomasDlg** [comment]
Проблема решилась обновлением до 0.3.2.

**Comment by andreyoshev** [comment]
У меня нет :/ 

Так же перестает отвечать через некоторое время.

**Comment by andreyoshev** [comment]
@efa2000 

<img width="129" alt="CleanShot 2020-05-13 at 02 14 38@2x" src="https://user-images.githubusercontent.com/17673010/81746256-95bbd200-94bf-11ea-8ec0-26aad3424db8.png">

```
 this.on('close',(done)=>{
      setTimeout(()=>{
        fb.auth().signOut();
        fb.delete().finally(r=>{done()});
      },500)
    });
```

Добавил сюда status `offline`, в какой-то момент падает и самостоятельно не поднимается.

**Comment by efa2000** [comment]
Duplicate of #5
