### ISSUE TITLE
есть возможность из node-red контролировать яндекс розетку?

### ISSUE THREAD

**Issue by ibyteyou** [efa2000/node-red-contrib-alice#41]
извиняюсь, не силён в этом, первый день ковыряю, подскажите пожалуйста если это возможно - то как примерно схема должна выглядеть?
- я хочу включать/выключать яндекс устройство из терминала локального пк по средствам node-red
- для соединения с яндексом можно использовать квазар или прописать свою полную авторизацию

**Comment by efa2000** [comment]
боюсь данный плагин вам не поможет 
этот плагин предназначен, что бы управлять любым устройством УЖЕ созданным в node-red голосом с колонки или из приложения яндексом

что бы посылать команды колонке или в квазар посмотрите вот на этот плаги 
[https://flows.nodered.org/node/node-red-contrib-yandex-alice-command](https://flows.nodered.org/node/node-red-contrib-yandex-alice-command)
