### ISSUE TITLE
Нода Color

### ISSUE THREAD

**Issue by semikor** [efa2000/node-red-contrib-alice#42]
Доброго время суток!
Будьте добры, можно в ноду Color добавить управление каналом white.
Использую совместно с https://github.com/tedstriker/node-red-contrib-magichome-controller а его с  WiFi RGBW https://aliexpress.ru/item/32883892255.html и не хватает управления каналом белого.
И еще раз, ОГРОМНОЕ СПАСИБО ЗА ТРУД!

**Comment by semikor** [comment]
Еще )) В ноде Range ставлю максимальную яркость на 255 (опять же для  WiFi RGBW), но в яндексе остается максимум 100%. Можно наверно как-то сконвертировать диапазон из 0-100 в 0-255, но пока не зная как...

**Comment by efa2000** [comment]
> Доброго время суток!
> Будьте добры, можно в ноду Color добавить управление каналом white.
> Использую совместно с https://github.com/tedstriker/node-red-contrib-magichome-controller а его с WiFi RGBW https://aliexpress.ru/item/32883892255.html и не хватает управления каналом белого.
> И еще раз, ОГРОМНОЕ СПАСИБО ЗА ТРУД!

к сожалению, здесь я ограничен возможностями Яндекса, а они пока не поддерживают управление каналом W
вы пошли правильным путем, создав через еще одно умение для устройства.

 

> Еще )) В ноде Range ставлю максимальную яркость на 255 (опять же для WiFi RGBW), но в яндексе остается максимум 100%. Можно наверно как-то сконвертировать диапазон из 0-100 в 0-255, но пока не знаю как...
> 
> Разобрался )) через range.

Да, к сожалению умение Яркость может быть только в процентах (по другому яндекс не понимает).
единственный способ это пересчитывать проценты в реальные значения

**Comment by semikor** [comment]
> к сожалению, здесь я ограничен возможностями Яндекса, а они пока не поддерживают управление каналом W

да, яндекс явно не в тренде, ведь еще есть и 5ти канальные модули (RGB + теплый и холодный белый).

Возникла еще какая-то не понятная для меня проблема (( 
Имею несколько модулей - один UFO Magic (такой круглый) теперь они не продаются, его Firmware Version 04.v5.12.6457-A и пара маленьких (как по ссылке выше) с Firmware Version 04.v5.14.6722-A. В Андроид приложении Magic Home все они работают без проблем (как и с z-wave контроллером Vera+), а вот в Node-Red полностью заработал только UFO, а маленькие (более современные) практически не работают  (срабатывают раз из десяти). Причину или какую-то зависимость так и не смог найти.
Может сможете что-нибудь посоветовать?
Спасибо!

**Comment by semikor** [comment]
Прошу прощения! Увлекся ))
Это мне к разработчику Magic Home...
