### ISSUE TITLE
Алиса и Zway сервер

### ISSUE THREAD

**Issue by gizmohex** [efa2000/node-red-contrib-alice#45]
Добрый день! В принципе во всех тонкостях node.red разобрался, даже скрипты уже освоил править/писать.
Поставил плагин для Алисы и впал в ступор... Добавил устройство типа выключатель, в панели яндекса оно появилоcь, на выход ноды подцепил debug...

Говорю команду - "Алиса включи свет на балконе", те то устройство которое через плагин добавлено в node.red и тишина...
Не понимаю, что она должна нода на выходе? Видимо, она не активируется?
И зачем вход нужен на ноде? что туда нужно передавать и в каком формате?

Планирую сценарий - добавить "виртуальные" девайсы через Ваш плагин в яндекс и далее после активации запускать сцены и другие наборы действий которые уже реализовал для UI

Буду благодарен Вам за любую помощь

**Comment by efa2000** [comment]
Добрый день 
на выходе ноды должны быть значения соответсвующие её типу 
посмотреть описание каждой ноды и типы значений которые будут на выходе и которые можно подать на вход описаны в разделе справки, там же есть описание по конфигурации 
![image](https://user-images.githubusercontent.com/6084441/91563751-12c46780-e948-11ea-8136-5467947dfba4.png)

В Вашем случае когда не выдается значение на выходе, есть вероятность, что при подачи команды с голоса Алиса не правильно определяет устройство которому отдается команда 
Попробуйте по включать устройства из интерфейса яндекса, там же где вы добавляли устройства
