### ISSUE TITLE
Нет возможности отключить random_access для range

### ISSUE THREAD

**Issue by Vinndimon** [efa2000/node-red-contrib-alice#49]
У умения _range_ может быть [отключён](https://yandex.ru/dev/dialogs/alice/doc/smart-home/concepts/range-instance-docpage/#range-instance__volume) параметр _random_access_, что крайне полезно для ИК-пультов. Например, чтобы прибавить или убавить звук на телевизоре, не устанавливая конкретное значение. Пожалуйста, добавьте возможность отключить random_access.

**Comment by efa2000** [comment]
не совсем понимаю проблему 
при включенном random, вы говорите алисе прибавить звук и она прибавляет на шаг 
отключение рендом приводит только к тому что отключаются кнопки с цифрами в итерфейсе яндекса

давайте попробуем на конкретном кейсе

**Comment by Vinndimon** [comment]
Ок, кейс следующий: у меня есть умный ИК-пульт, который управляет телевизором. При этом нет обратной связи - я не знаю, какой сейчас на телевизоре уровень громкости. Поэтому при включённом random access я могу прибавлять громкость ограниченное количество раз, и не факт, что оно совпадает с реальными значениями на телевизоре: Алиса считает, что громкость - 100 из 100 и больше не может посылать команду "повысить громкость", хотя реальная громкость на телевизоре может быть совсем другой.

Нужно иметь возможность добавить в Алису кнопки, просто повышающие или понижающие громкость. Вне зависимости от того, какой сейчас установлен уровень.

**Comment by efa2000** [comment]
Добрый день, 
да, спасибо за кейс. теперь проблема более понятна
но это тогда не random_access, это параметр retrievable который как раз и отвечает за то знает ли Алиса текущее значение или нет 
и если установить его в false, то на выходе из ноде всегда будет не конкретное значение которое нужно установить, а значение на сколько нужно прибавить, или со знаком минус значение на которое нужно уменьшить

**Comment by Vinndimon** [comment]
Рад, что удалось разъяснить ситуацию. Вам виднее, о какой опции идёт речь. Но описание random access говорит вот что:

`Возможность устанавливать произвольные значения функции. Если эта возможность выключена, пользователю будет доступно только последовательное изменение значений — в большую или меньшую сторону. Например, изменение громкости телевизора при работе через ИК пульт.`

**Comment by efa2000** [comment]
ок, я добавлю возможность настройки этого параметра в следущим релизе

**Comment by efa2000** [comment]
Добавил для ноды Range возможность получить на выходе не финальное значение, а только дельту на которую нужно прибавить или убавить 
Мне не очень нравится как это реализовано из интерфейса самого яндекса. но там я уже поделать к сожалению ни чего не могу

**Comment by Vinndimon** [comment]
@efa2000 обновился до 0.4.2. Не очень понимаю, как это решает задачу с повышением/уменьшением громкости без указания её точного значения. Вот так у меня выглядит настройка ноды: 
![image](https://user-images.githubusercontent.com/4707428/99273760-82a50880-283a-11eb-8e57-c7793eb81089.png)
А вот так - панель управления телевизором: 
![image](https://user-images.githubusercontent.com/4707428/99274273-33130c80-283b-11eb-9758-5a3ccd8a1827.png)

А нужно, чтобы были всегда активные кнопки +/-, без цифр.

**Comment by efa2000** [comment]
поставьте версию 0.4.3 там был небольшой баг с галочкой 
и не забудет после изменения настройки ноды сделать deploy и обновить список устройств в интерфейсе яндекса 
в итоге выглядит все примерно так 
на выходе у вас будут значения 1 / -1 (число может отличаться, к примеру если вы через ализу попросите прибавить звук на 20, основное здесь положительное или отрицательное число )

![Uploading image.png…]()

**Comment by Vinndimon** [comment]
@efa2000 к сожалению, скриншот не загрузился. Поэтому не могу увидеть, как должно быть. Обновился до 0.4.3 - настройки ноды у меня не изменились, количество галочек всё то же.

**Comment by efa2000** [comment]
Извините, сейчас очень большая загрузка не могу оперативно отвечать
в итоге у вас должна быть снята галочка как на снимке и на выходе будете иметь положительное отрицательное значение 
![image](https://user-images.githubusercontent.com/6084441/102272015-26b0cb00-3f31-11eb-9662-6e1c22b0a22b.png)

**Comment by efa2000** [comment]
Как галочка то помогла? Удалось сделать, что планировали?
