### ISSUE TITLE
Спустя сутки Алиса перестает принимать команды

### ISSUE THREAD

**Issue by andreyoshev** [efa2000/node-red-contrib-alice#5]
Спустя где-то сутки Алиса перестает принимать команды. 
Устройства не реагируют, хотя везде `online`, в debug также ничего не валится после команды. 
Помогает deploy.

**Comment by efa2000** [comment]
в версии 0.3.4 добавил ежеминутную проверку на доступность хоста 
после восстановления интернета, ноды переподключаются 
напишите плиз по результатам

**Comment by andreyoshev** [comment]
@efa2000 не помогло, алиса все равно иногда не засылает команды в НР, хотя везде `online`.

**Comment by moiseyev** [comment]
Привет, всем. У меня похожая проблема, правда не через сутки, а по-разному, но периодически ноды переходят в статус offline и нужно заходить в node-red и нажимать Restart Flows чтобы они снова переходили в статус online (интернет на устройстве с node-red присутствует), возможно это случается после отключения электричества в доме,  пока наблюдаю и пытаюсь собрать как можно больше информации.

**Comment by efa2000** [comment]
> Привет всем. У меня похожая проблема, правда не через сутки, а по-разному, но периодически ноды переходят в статус offline и нужно заходить в node-red и нажимать Restart Flows чтобы они снова переходили в статус online (интернет на устройстве с node-red присутствует), возможно это случается после отключения электричества в доме, пока наблюдаю и пытаюсь собрать как можно больше информации.

какая версия плагина у Вас установлена?

**Comment by moiseyev** [comment]
> какая версия плагина у Вас установлена?

Установлена 0.3.13
Только сейчас, когда пошёл смотреть версию, заметил кнопку "update to 0.4.1" в Manage palette. Обновляю.

**Comment by efa2000** [comment]
ошибка больше не повторялась ?

**Comment by sko2006** [comment]
Здравствуйте. Установил плагин 0.5.3. Ноды on_off. Периодически не доходят сообщения от Алисы. И заметил чем больше нодов добавляю, тем больше пропусков.

**Comment by efa2000** [comment]
> Здравствуйте. Установил плагин 0.5.3. Ноды on_off. Периодически не доходят сообщения от Алисы. И заметил чем больше нодов добавляю, тем больше пропусков.

А Алиса при этом отвечает, что устройства не доступны?

**Comment by sko2006** [comment]
Нет горит зелёный online

**Comment by efa2000** [comment]
В связи с выходом версии 1.0.0
Более не актуально
