### ISSUE TITLE
Невозможно связать с аккаунтом Яндекса

### ISSUE THREAD

**Issue by Vinndimon** [efa2000/node-red-contrib-alice#52]
При попытке авторизации в плагине NodeRed Home вылезает ошибка:
`https://api.node-red-alice.ru/authorize: 0 Unknown Error`
Логин и пароль точно верные.

**Comment by efa2000** [comment]
Похоже была проблема с сертификатом на сервере 
поправил, попробуйте

**Comment by Vinndimon** [comment]
Спасибо, заработало!
