### ISSUE TITLE
Не обновляется список устройств у Алисы

### ISSUE THREAD

**Issue by DmitrySlav** [efa2000/node-red-contrib-alice#57]
Добрый день. Я только начал работу с node-red-contrib-alice и столкнулся с проблемой. Я создал аккаунт в Яндекс добавил устройство On_Off, привязанное к аккаунту, но после обновления списка устройств, получаю сообщение, что у меня актуальный список устройств. При этом устройство в списке у Яндекса отсутствует. Не могу понять, что я делаю не так.  
![2020-10-24_14-42-41](https://user-images.githubusercontent.com/66067280/97080873-4ef20c80-1607-11eb-8232-91c41a3ea2d3.png)

**Comment by efa2000** [comment]
Очень странная ситуация 
Попробуйте удалить устройство из nodered, а в интерфейсе Яндекса выйти из навыка. 
Затем создайте заново устройство и заново в интерфейсе Яндекса подключитесь к навыку NodeRedHome
