### ISSUE TITLE
Нода Range

### ISSUE THREAD

**Issue by TomasDlg** [efa2000/node-red-contrib-alice#6]
node-red-contrib-alice v. 0.3.1
Как правильно настроить ноду Range?
1)Добавляю ноду Range, 
2)выбираю устройство телевизор (при этом это устройство уже добавлено нодой On_Off),
3) Выбираю Range type volume, остальные параметры оставляю по умолчанию,
4) Обновляю список устройств в Яндексе.
Управление звуком не появляется, могу только вкл/выкл телевизор.
Затем я удалил устройство телевизор из Яндекса. Обновил список устройств, но телевизор не добавился в Яндексе (в node-red все ноды имеют статус online). Только после удаления ноды Range обновления списка устройств, телевизор появился как новое устройств и по прежнему доступно только управление вкл/выкл.
Что я делаю не так?

**Comment by exotsk** [comment]
У телевизора range не работает для громкости, нода не появляется. 
Но успешно работает на чайнике в температуре и яркости на ленте. так же в параллель с on off color и т.п.

**Comment by efa2000** [comment]
вы все правильно делаете 
нашел ошибку, яндекс странно обрабатывает один параметр 
сегодня-завтра выпушу апдейт, в котором это будет устранено

**Comment by efa2000** [comment]
исправлено в версии 0.3.2
как будет доступна, обновите и сделайте редеплой
должно исправится 

по возможности отпишитесь о результатах

**Comment by exotsk** [comment]
Спасибо! Очень нужный проект, и удобный

**Comment by efa2000** [comment]
Очень рад! :)

**Comment by TomasDlg** [comment]
Управление громкостью появилось. Спасибо.
