### ISSUE TITLE
Статус offline для всех навыков кроме on/off

### ISSUE THREAD

**Issue by aleksandrdobrynin** [efa2000/node-red-contrib-alice#61]
После обновления на 0.4.2 статус всех навыков кроме on/off отображается как offline.
![image](https://user-images.githubusercontent.com/32413181/99350439-6c855f80-28af-11eb-8ec4-f22a249b8e13.png)

**Comment by efa2000** [comment]
да, там был небольшой баг 
уже выложил 0.4.3

**Comment by aleksandrdobrynin** [comment]
Ситуация не изменилась (
![image](https://user-images.githubusercontent.com/32413181/99360173-3f41ad00-28c1-11eb-92e5-ecf0f67412ce.png)

**Comment by efa2000** [comment]
что то у меня не воспроизводится :(
попробую еще посмотреть

**Comment by aleksandrdobrynin** [comment]
У меня есть основной девайс – лампа. Для неё создаю навык on/off. Затем беру навык range и выбираю ранее созданный девайс (лампа on/off). Настраиваю range на изменения яркости в диапазоне от 1 до 100 с шагом 1. Делаю full деплой. Получаю картинку как на скрине выше. В 0.4.1 все работало четко. Никаких изменений с номой Алиса не производил.

А что нового появилось в последних версиях? Может нет смысла обновляться? )

**Comment by aleksandrdobrynin** [comment]
Нет ли новостей?

**Comment by efa2000** [comment]
новое только в range добавилась галочка которая на выход подает или полное значение которое нужно установить или только изменение на которое нужно прибавить или убавить 
это какая то неведомая вещь, у меня не воспроизводится :(
видимо пришло время обновить firebase 
сделал сборку с последней версией 

версия 0.4.4

**Comment by aleksandrdobrynin** [comment]
Обновил. Ситуация не изменилась.
![image](https://user-images.githubusercontent.com/32413181/100330787-6e9e9b00-2fe0-11eb-9603-6669a113eb6d.png)

**Comment by efa2000** [comment]
При этом яркость работает? Просто статус не показывает?

**Comment by aleksandrdobrynin** [comment]
Да, работает, если отправляю команду на изменение яркости голосом, то она меняется. В NR выглядит при этом так
![image](https://user-images.githubusercontent.com/32413181/102336686-8eebc500-3fa2-11eb-93c1-8b3b40201177.png)

**Comment by efa2000** [comment]
в последнем релизе полностью переработана работа со статусами устройств
