### ISSUE TITLE
Не соединяется с сервером 

### ISSUE THREAD

**Issue by VVovaer** [efa2000/node-red-contrib-alice#63]
в логах node-red ругается так:
|node-red  | [2020-11-25T16:16:21.077Z]  @firebase/firestore: Firestore (7.24.0): Connection GRPC stream error. Code: 13 Message: 13 INTERNAL: Request message serialization failure: util.Long.fromValue is not a function

система linux,  

 ~/.node-red # npm list firebase
node-red-project@0.0.1 /user/.node-red
└─┬ node-red-contrib-alice@0.4.3
  └── firebase@7.24.0

**Comment by efa2000** [comment]
Обновил версию firebase 
Попробуйте обновится на последнюю сборку которую я выложил 0.4.4

**Comment by VVovaer** [comment]
что-то не тотоже самое,  в сообщениях обновиласть только версии firestore 8.1.1 теперь.

но проблемы видимо есть, после переустановки 
make: вход в каталог «/root/.node-red/node_modules/zmq/build»
  CXX(target) Release/obj.target/zmq/binding.o
../binding.cc:28:10: фатальная ошибка: zmq.h: Нет такого файла или каталога
   28 | #include <zmq.h>
      |          ^~~~~~~
компиляция прервана.
make: *** [zmq.target.mk:107: Release/obj.target/zmq/binding.o] Ошибка 1
make: выход из каталога «/root/.node-red/node_modules/zmq/build»
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib64/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.57-calculate
gyp ERR! command "/usr/bin/node" "/usr/lib64/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/.node-red/node_modules/zmq
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs-ext@0.5.0 (node_modules/fs-ext):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs-ext@0.5.0 install: `node-gyp configure build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: snappy@5.0.5 (node_modules/snappy):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: snappy@5.0.5 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: leveldown@1.4.6 (node_modules/leveldown):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: leveldown@1.4.6 install: `prebuild --install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 2
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: zmq@2.15.3 (node_modules/zmq):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: zmq@2.15.3 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ node-red-contrib-alice@0.4.4
updated 1 package and audited 681 packages in 45.006s

**Comment by efa2000** [comment]
Так ну в итоге он проинсталился и работает?
Ошибка которая была раньше всплывает?

**Comment by VVovaer** [comment]
ошибка теперь такая :
[2020-11-26T04:54:51.671Z]  @firebase/firestore: Firestore (8.1.1): Connection GRPC stream error. Code: 13 Message: 13 INTERNAL: Request message serialization failure: util.Long.fromValue is not a function
изменилась версия firestore

**Comment by VVovaer** [comment]
в общем обновил node-red до 1.2.6  и node-red-contrib-alice и всё заработало

**Comment by VVovaer** [comment]
удалось исправить полной переустановкой nodejs? node-red и node-red-contrib-alice
Пока работает. понаблюдаем
