### ISSUE TITLE
Поддержка устройств типа sensor

### ISSUE THREAD

**Issue by valekrus** [efa2000/node-red-contrib-alice#67]
Хотелось бы уточнить - планируется ли поддержка датчиков?

Со стороны Яндекс такой тип устройств поддерживается: https://yandex.ru/dev/dialogs/alice/doc/smart-home/concepts/device-type-sensor.html/

**Comment by efa2000** [comment]
Да, планируется 
единственное сейчас очень большая загрузка по основной работе, замет некоторое время

**Comment by sanyafifa** [comment]
Плюсую

**Comment by algar42** [comment]
дааа, очень бы хотелось работу с датчиками!! Тем более, что новое АПИ яндекса теперь позволяет даже запрашивать информацию с них голосом, а не только в квазаре их видеть :)

**Comment by efa2000** [comment]
Да, вот как раз ими родными и занимаюсь, почти доделал

**Comment by sanyafifa** [comment]
> Да, вот как раз ими родными и занимаюсь, почти доделал

Готов к тестированию ;)

**Comment by efa2000** [comment]
Версия 0.5.1
Есть сенсоры, но Яндекс сенсоры типа движения и датчик открытия (контакт) держит в статусе бета и доступ к ним мне пока не открыл. 
По этому пока доступны только сенсоры которые передают число 

Как только откроют обновлю

**Comment by sanyafifa** [comment]
> Версия 0.5.1

Спасибо!
Проверил, вроде ОК. 

А то что датчик в виде лампочки, это у всех так?
![image](https://user-images.githubusercontent.com/49896945/105032100-5c346100-5a67-11eb-9745-355493aa203c.png)


> Яндекс сенсоры типа движения и датчик открытия (контакт)

Вроде как Алиса сама не умеет диалог инициировать? какая там логика в булевых сенсорах...

**Comment by efa2000** [comment]
> 
> А то что датчик в виде лампочки, это у всех так?
> ![image](https://user-images.githubusercontent.com/49896945/105032100-5c346100-5a67-11eb-9745-355493aa203c.png)

Нет, ты просто привязал датчик к устройству типа свет :) 
там при создании устройства надо выбрать тип sensor

> 
> > Яндекс сенсоры типа движения и датчик открытия (контакт)
> 
> Вроде как Алиса сама не умеет диалог инициировать? какая там логика в булевых сенсорах...
да, пока не умеет, но я думаю в планах у них есть, и они что то тестируют и по этому пока не всем дают

**Comment by algar42** [comment]
дааа, красота. Вроде все работает как надо! Спасибо!
![sensors](https://user-images.githubusercontent.com/40002726/105138582-23979480-5b06-11eb-98a0-9eca44a8493e.jpg)

Теперь ждем булевых сенсоров ;)

**Comment by efa2000** [comment]
> Теперь ждем булевых сенсоров ;)

Поддержка Яндекса наконец то ответила. Доступ к булевым сенсорам не дали, сказали ждите официального релиза :(
