### ISSUE TITLE
Не принимает MQTT после рестарта nodered

### ISSUE THREAD

**Issue by exotsk** [efa2000/node-red-contrib-alice#7]
![image](https://user-images.githubusercontent.com/54969124/81094911-6d1b6180-8f2e-11ea-9ed6-0334471a9cd2.png)
вот такой конфиг, после рестарта не принимает boolean.
Далее делаю deploy, пишет что нода в оффлайне. онлай восстанавливается после рестарта контейнера. На докере все, mosquitto, node-red

**Comment by exotsk** [comment]
06.05.2020, 00:20:04node: 96073d78.af184
msg.payload : boolean
true
06.05.2020, 00:20:04node: 96073d78.af184
msg.payload : boolean
true
06.05.2020, 00:20:04node: 96073d78.af184
msg.payload : boolean
true
06.05.2020, 00:20:04node: Кабинет: Кабинет
msg : string[14]
"Device offline"
06.05.2020, 00:20:04node: Кабинет: Кабинет
msg : string[14]
"Device offline"
06.05.2020, 00:20:04node: Кабинет: Кабинет
msg : string[14]
"Device offline"
06.05.2020, 00:20:05node: Кабинет: Кабинет
msg : string[14]
"Device offline"
06.05.2020, 00:20:05node: Кабинет: Кабинет
msg : string[14]
"Device offline"
06.05.2020, 00:20:05node: Кабинет: Кабинет
msg : string[14]
"Device offline"
----------------------
06.05.2020, 00:19:51 [Кабинет] Received MQTT: stat/CABINET/POWER = ON
06.05.2020, 00:19:51 [Кабинет] Received MQTT: stat/CABINET/POWER = ON
06.05.2020, 00:19:55 [Кабинет] Received MQTT: stat/CABINET/POWER = OFF
06.05.2020, 00:19:55 [Кабинет] Received MQTT: stat/CABINET/POWER = OFF
06.05.2020, 00:19:55 [Кабинет] Received MQTT: stat/CABINET/POWER = OFF
06.05.2020, 00:20:03 [Кабинет] Received MQTT: stat/CABINET/POWER = ON
06.05.2020, 00:20:03 [Кабинет] Received MQTT: stat/CABINET/POWER = ON
06.05.2020, 00:20:03 [Кабинет] Received MQTT: stat/CABINET/POWER = ON
________________________________________________________________________________
Если пытаться переключать со стороны яндекса "оффлайновый" девайс, начинает слать дубликаты по 2 -3 раза. После рестарта же, когда пишет онлайн, все ок, один раз

**Comment by exotsk** [comment]
Все заходит, индикации нет, но статус на яндексе меняется отлично.
Отавлы и дубликаты после 0,3,2 вроде прекратились. Можно закрывать! Спасибо.

**Comment by efa2000** [comment]
возможно здесь специфика работы firebase по подписке на данные
в версии 0.3.2 firebase был обновлен до последнего актуального
