### ISSUE TITLE
Не работает On/Off на мультиварке

### ISSUE THREAD

**Issue by vring0** [efa2000/node-red-contrib-alice#71]
Не меняется статус On/Off на мультиварке. Если менять в Яндексе On/Off, то ответ в ноду прилетает. Версия 0.4.4
![image](https://user-images.githubusercontent.com/34909289/103288393-9a110d00-4a06-11eb-9e31-50f3f9420861.png)

**Comment by efa2000** [comment]
вы имеете ввиду сели вы посылаете статус в ноде, то он не отображается в интерфейсе яндекса?

**Comment by vring0** [comment]
> вы имеете ввиду сели вы посылаете статус в ноде, то он не отображается в интерфейсе яндекса?

Верно всё

**Comment by efa2000** [comment]
> > вы имеете ввиду сели вы посылаете статус в ноде, то он не отображается в интерфейсе яндекса?
> 
> 
> 
> Верно всё. Если на яндексе меняем On/Off , обратка в ноду прилетает. 

С выходом сенсоров Яндекс походу поменял режим опроса девайсов при отображении в интерфейсе 
Попробуйте зайти внутрь устройства в интерфейсе Яндекса там статус должен отображаться корректно

А корректное отображение статуса на главной странице я исправлю когда добавлю поддержку сенсоров

**Comment by vring0** [comment]
> > > вы имеете ввиду сели вы посылаете статус в ноде, то он не отображается в интерфейсе яндекса?
> > 
> > 
> > Верно всё. Если на яндексе меняем On/Off , обратка в ноду прилетает.
> 
> С выходом сенсоров Яндекс походу поменял режим опроса девайсов при отображении в интерфейсе
> Попробуйте зайти внутрь устройства в интерфейсе Яндекса там статус должен отображаться корректно
> 
> А корректное отображение статуса на главной странице я исправлю когда добавлю поддержку сенсоров

Всё получилось! Спасибо
