### ISSUE TITLE
Устройства не доступны.

### ISSUE THREAD

**Issue by megavoltt** [efa2000/node-red-contrib-alice#72]
Скажите как в Node red понять что устройства не доступны. Для чего поясню, периодически устройства недоступны, для чего требуется перезапуск Node red. Вот и хотел поймать момент отключения устройств для перезагрузки Node red. Спасибо

**Comment by efa2000** [comment]
А в логах ничего нет?

**Comment by megavoltt** [comment]
если вы про debug в node red, то ни чего в момент disconnect устройств, хотя node red показывает что устройства подключены

**Comment by efa2000** [comment]
> если вы про debug в node red, то ни чего в момент disconnect устройств, хотя node red показывает что устройства подключены

Нет, я имею ввиду лог самой ноде ред, в консоли 

Устройства в ноде пока не могут проверять доступность, было в планах это доделать, но пока руки не дошли 

Мне собственно интересно почему они в принципе отваливаются :( 
Даже если было коротковоеменное проседание интернета, они должны сами восстановится

**Comment by algar42** [comment]
Кстати, поймал такой глюк на днях на версии 0.5.2.  Пробую включить свет, а колонка говорит, что устройство недоступно. Захожу в NR показывает, что все ноды алисы онлайн. Редеплой помог. Все в сети появилось. 
Никаких ошибок в логах не было.

**Comment by efa2000** [comment]
Если пару дней назад, то это связано с другим.
Были проблемы с правами доступа к базе, устройства видели базу но писать в неё не могли.

**Comment by algar42** [comment]
> Если несколько дней назад, то это связано с другим.
> Были проблемы с правами доступа к базе, устройства видели базу но писать в неё не могли.

ааааа, тогда да, возможно так и было
