### ISSUE TITLE
ошибка при создании сенсора

### ISSUE THREAD

**Issue by bonuzzz** [efa2000/node-red-contrib-alice#76]
создаю устройство, например other или sensor. выбираю элемент sensor. он сразу в оффлайне. при отправке значения  получаю в логах ошибку "TypeError: Cannot read property 'collection' of null"

**Comment by efa2000** [comment]
А вы при деплое схемы нажимаете full deploy или только изменённые компоненты ?

**Comment by bonuzzz** [comment]
full
выключатели работают. температура через термостат тоже

**Comment by sanyafifa** [comment]
`[error] [Sensor:Спальня:влажность] TypeError: Cannot read property 'collection' of null`

у меня такую ошибку только сенсор влажности показывает. при старте NR. Ему передаю числовое значение. пример -  51.17

**Comment by bonuzzz** [comment]
@sanyafifa а с температурой норм?

**Comment by sanyafifa** [comment]
> @sanyafifa а с температурой норм?
> попробовал еще раз.у меня даже до передачи данных сенсор в оффлайн уходит

да и влажность потом норм работает. Но в логах каждый раз при деплое ругается
![image](https://user-images.githubusercontent.com/49896945/106390995-e49cf500-63c9-11eb-8edc-c6f1c870e049.png)

**Comment by efa2000** [comment]
ошибка у меня плохо воспроизводится, но поправил все места где теоретически могла возникать 
попробуйте обновится на версию 0.5.3

**Comment by sanyafifa** [comment]
> ошибка у меня плохо воспроизводится, но поправил все места где теоретически могла возникать
> попробуйте обновится на версию 0.5.3

Без изменений, на работу не влияет. лог:
`2 Feb 19:19:29 - [info] Node-RED version: v1.2.7`
`2 Feb 19:19:29 - [info] Node.js  version: v10.23.2`
`2 Feb 19:19:29 - [info] Linux 5.10.11-v7l+ arm LE`

`2 Feb 19:19:36 - [error] [Sensor:Спальня:влажность:Humidity] TypeError: Cannot read property 'collection' of undefined`

**Comment by efa2000** [comment]
Вот блин :( 
В докере я не тестил, надо разбираться, что происходит 

Я тут как раз канал в телеграмм хотел запустить для новостей и оперативной поддержке 

Давайте завтра в нем и обсудим 
[https://t.me/nodered_home](https://t.me/nodered_home)

**Comment by efa2000** [comment]
А я правильно понимаю, что у всех кого возникает эта ошибка, он вас контейнере? 
Ещё смущает node v10 я использую только v12

**Comment by bonuzzz** [comment]
у меня в официальном контейнере. версия 10ая стоит

**Comment by bonuzzz** [comment]
@efa2000 вы похоже канал сделали, а не группу. написать туда нет возможности

**Comment by efa2000** [comment]
да, сорри вот группа https://t.me/joinchat/SsKo3bjfQDLkMnbD
я телеграмм немного не долюбливаю :)

**Comment by algar42** [comment]
Такая ошибка у меня выскакивала во время деплоя когда устройство на входе в ноду пытается записать в него значение до перехода ноды в онлайн. Поставил на вход задержки в 5 секунд чтобы дать возможность алисе проинициализироваться и эта ошибка пропала. 
Node V12 кстати. работает норм все.

**Comment by efa2000** [comment]
Да, после деплоя нужно пару секунд.
Что бы все устройства обновили статус 
Если это только сразу после деплоя, и потом все корректно шлётся, то я просто добавлю красивую обработку этой ошибки

**Comment by algar42** [comment]
да, у меня потом все корректно работает

**Comment by sanyafifa** [comment]
> Такая ошибка у меня выскакивала во время деплоя когда устройство на входе в ноду пытается записать в него значение до перехода ноды в онлайн. Поставил на вход задержки в 5 секунд чтобы дать возможность алисе проинициализироваться и эта ошибка пропала.
> Node V12 кстати. работает норм все.

спасибо за подсказку.
да, была нода mqtt с флагом retainна входе.
 Поставил ноду trigger на 5 сек. Ошибка пропала. :)

**Comment by bonuzzz** [comment]
зашел сейчас в ноду, чтобы проверить. все датчики в онлайне. даже те, кто изначально сразу был в оффлайн. создал сенсор и работает сразу. в общем, чудо чудное. с моей стороны ничего не трогал, не обновлял итд. некогда было
