### ISSUE TITLE
Появились режимы заваривания чая

### ISSUE THREAD

**Issue by vring0** [efa2000/node-red-contrib-alice#77]
https://yandex.ru/dev/dialogs/alice/doc/smart-home/concepts/mode-instance.html#mode-instance__tea_mode

![image](https://user-images.githubusercontent.com/34909289/106285837-c5398700-6266-11eb-8af5-7d44588bb95d.png)

**Comment by efa2000** [comment]
Да, ок, добавлю в ближайшем релизе

**Comment by efa2000** [comment]
добавлено в версии  0.5.3

**Comment by vring0** [comment]
Спасибо! Теперь можно говорить какой напиток нужен) а то постоянно говорю температуру цифрами
